ARG GOLANG="golang:1.15-alpine3.14"

FROM --platform=${BUILDPLATFORM} ${GOLANG} AS builder
WORKDIR /nps/
COPY ./ ./
RUN go mod download -x
ARG TARGETARCH
ENV GOOS=linux GOARCH=${TARGETARCH} CGO_ENABLED=0
RUN go build -v -trimpath -ldflags "-s -w -extldflags -static" ./cmd/nps/nps.go

FROM scratch AS web
WORKDIR /nps/web/
COPY ./web/views/ ./views/
COPY ./web/static/ ./static/

FROM scratch
COPY --from=web /nps/web/ /web/
COPY --from=builder /nps/nps /usr/bin/nps
ENTRYPOINT ["nps"]
